version: '1'
services:
  tienda-ms-pedidos:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8094:8094"
    environment:
      - spring.datasource.url=jdbc:oracle:thin:@vocgyi3vv1p3nvr8_tp?TNS_ADMIN=/app/wallet/
      - spring.datasource.username=BDFS3_PEDIDOS
      - spring.datasource.password=ClaseFullStack3-
    restart: always